### ISSUE TITLE
Error when trying to create new organization.

### ISSUE THREAD

**Issue by ADmad** [sulu/sulu#4232]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 2.0.0-alpha4

Got error message when trying to create new organization by providing just the "Name".

The POSTed data was:
```
corporation | null
logo | null
name | test
note | null
parent | null
uid | null
```

The exception thrown for the POST request is:

```
{
    "code": 0,
    "message": "Warning: array_key_exists() expects parameter 2 to be array, null given",
    "errors": [
        "ErrorException: Warning: array_key_exists() expects parameter 2 to be array, null given in /srv/sites/sulu/vendor/sulu/sulu/src/Sulu/Bundle/ContactBundle/Controller/AccountController.php:503\nStack trace:\n#0 /srv/sites/sulu/vendor/sulu/sulu/src/Sulu/Bundle/ContactBundle/Controller/AccountController.php(458): Sulu\\Bundle\\ContactBundle\\Controller\\AccountController->doPost(Object(Symfony\\Component\\HttpFoundation\\Request))\n#1 /srv/sites/sulu/vendor/symfony/http-kernel/HttpKernel.php(149): Sulu\\Bundle\\ContactBundle\\Controller\\AccountController->postAction(Object(Symfony\\Component\\HttpFoundation\\Request))\n#2 /srv/sites/sulu/vendor/symfony/http-kernel/HttpKernel.php(66): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#3 /srv/sites/sulu/vendor/symfony/http-kernel/Kernel.php(188): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#4 /srv/sites/sulu/public/admin.php(58): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#5 /srv/sites/sulu/public/app.php(13): require_once('/srv/sites/sulu...')\n#6 /srv/sites/sulu/vendor/symfony/web-server-bundle/Resources/router.php(42): require('/srv/sites/sulu...')\n#7 {main}"
    ]
}
```

So it seems an additional check to ensure return value for `$request->get('logo', [])` is not `null` before trying to use `array_key_exists()`.

**Comment by danrot** [comment]
Will be fixed in #4266.
