### ISSUE TITLE
Call to a member function getProperties() on null in ManagedStructure.php line 171

### ISSUE THREAD

**Issue by stollr** [sulu/sulu#7031]
| Q | A
| --- | ---
| Sulu Version | 2.5.7
| PHP Version | 8.2.3
| DB Version | irrelevant
| Browser Version | irelevant

# Actual Behavior

When I try to remove a page from the webspace I get the following error:
```
Error: Call to a member function getProperties() on null in /srv/htdocs/myproject/vendor/sulu/sulu/src/Sulu/Component/Content/Document/Structure/ManagedStructure.php:171
Stack trace:
#0 /srv/htdocs/myproject/vendor/sulu/sulu/src/Sulu/Bundle/PageBundle/Trash/PageTrashItemHandler.php(116): Sulu\\Component\\Content\\Document\\Structure\\ManagedStructure->toArray()
#1 /srv/htdocs/myproject/vendor/sulu/sulu/src/Sulu/Bundle/TrashBundle/Application/TrashManager/TrashManager.php(77): Sulu\\Bundle\\PageBundle\\Trash\\PageTrashItemHandler->store()
#2 /srv/htdocs/myproject/vendor/sulu/sulu/src/Sulu/Bundle/PageBundle/EventListener/PageTrashSubscriber.php(75): Sulu\\Bundle\\TrashBundle\\Application\\TrashManager\\TrashManager->store()
#3 /srv/htdocs/myproject/vendor/symfony/event-dispatcher/EventDispatcher.php(246): Sulu\\Bundle\\PageBundle\\EventListener\\PageTrashSubscriber->storePageToTrash()
#4 /srv/htdocs/myproject/vendor/symfony/event-dispatcher/EventDispatcher.php(206): Symfony\\Component\\EventDispatcher\\EventDispatcher::Symfony\\Component\\EventDispatcher\\{closure}()
#5 /srv/htdocs/myproject/vendor/symfony/event-dispatcher/EventDispatcher.php(56): Symfony\\Component\\EventDispatcher\\EventDispatcher->callListeners()
#6 /srv/htdocs/myproject/vendor/sulu/sulu/src/Sulu/Component/DocumentManager/DocumentManager.php(67): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch()
#7 /srv/htdocs/myproject/vendor/sulu/sulu/src/Sulu/Bundle/PageBundle/Controller/PageController.php(432): Sulu\\Component\\DocumentManager\\DocumentManager->remove()
#8 /srv/htdocs/myproject/vendor/sulu/sulu/src/Sulu/Component/Rest/RestControllerTrait.php(146): Sulu\\Bundle\\PageBundle\\Controller\\PageController->Sulu\\Bundle\\PageBundle\\Controller\\{closure}()
#9 /srv/htdocs/myproject/vendor/sulu/sulu/src/Sulu/Bundle/PageBundle/Controller/PageController.php(438): Sulu\\Component\\Rest\\AbstractRestController->responseDelete()
#10 /srv/htdocs/myproject/vendor/symfony/http-kernel/HttpKernel.php(163): Sulu\\Bundle\\PageBundle\\Controller\\PageController->deleteAction()
#11 /srv/htdocs/myproject/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw()
#12 /srv/htdocs/myproject/vendor/symfony/http-kernel/Kernel.php(184): Symfony\\Component\\HttpKernel\\HttpKernel->handle()
#13 /srv/htdocs/myproject/public/index.php(66): Symfony\\Component\\HttpKernel\\Kernel->handle()
#14 {main}"
```

# Expected Behavior

The page is removed

# Steps to Reproduce

* Create a page template config file
* create a page in the admin area based on the new template config
* delete the template config file
* try to delete the page from the webspace

# Possible Solutions

Imho this error should be catched/handled and the page should just be removed completely.

**Comment by remdan** [comment]
having the same just after update from 2.5.6 to 2.5.8... loading the snippet-list in admin is not possible

**Comment by alexander-schranz** [comment]
If you are removing renaming a page template like in here in the step:

> delete the template config file

It will fail, this is unexpected. Every change in your templates XML which could break existing data requires a PHPCR mgiration, as example: 

https://docs.sulu.io/en/2.5/cookbook/migrate-content-data.html

Sulu expected that the return data in your database matches your `metadata` if that is not the case it can error in unexpected cases.

**Comment by stollr** [comment]
That makes definitely sense. Thanks for the hint.
But still I'd expect that the variable's value is checked, before accessing it to prevent the function call on null. Ideally an exception would be thrown that contains this hint ;-)

I'll have a look and try to create a PR.

**Comment by stollr** [comment]
@alexander-schranz While trying to write a patch. I wonder about the return declaration of [`Sulu\Component\Content\Metadata\Factory\StructureMetadataFactoryInterface::getStructureMetadata`](https://github.com/sulu/sulu/blob/ebaab29cb35155e44005305f3973764562da6eac/src/Sulu/Component/Content/Metadata/Factory/StructureMetadataFactoryInterface.php#L24). It is defined as `StructureMetadata|null` but as far as I see, the result of the call is never checked for nullability.

Does it make sense to change the return type to `StructureMetadata` only and throw an exception instead of returning null? Or is there a valid reason why this method may return `null`?

I suggest throwing an exception there and tell the user what the reason is.

What do you think?

**Update**:
Right after sending the comment, I realized that a `StructureTypeNotFoundException` is already thrown (in dev mode), but it is catched in the [`DocumentInspector`](https://github.com/sulu/sulu/blob/ebaab29cb35155e44005305f3973764562da6eac/src/Sulu/Bundle/DocumentManagerBundle/Bridge/DocumentInspector.php#L120) and null is returned.

So I suggest removing the catching of the exception or adding a check everywhere where `DocumentInspector::getStructureMetadata` is called.
