### ISSUE TITLE
Cache provided for type "meta" is Doctrine\Common\Cache\Psr6\DoctrineProvider which does not imple     ment Psr\SimpleCache\CacheInterface.

### ISSUE THREAD

**Issue by lesmyrmidons** [sulu/sulu#7705]
| Q | A
| --- | ---
| Sulu Version | 2.6.5|2.6.6
| PHP Version | 8.3.14-fpm-alpine3.21
| DB Version |  MySQL 8

# Actual Behavior

The `cache:clear` command, in prod or stage environment, returns this error 
```
Cache provided for type "meta" is Doctrine\Common\Cache\Psr6\DoctrineProvider which does not imple  
  ment Psr\SimpleCache\CacheInterface in /var/www/html/vendor/sulu/sulu/src/Sulu/Bundle/PageBundle/R  
  esources/config/routing_api.yml (which is being imported from "/var/www/html/config/routes/sulu_ad  
  min.yaml"). Make sure there is a loader supporting the "rest" type.                                 
                                                                                                      

In CachedClient.php line 44:
                                                                                                      
  Cache provided for type "meta" is Doctrine\Common\Cache\Psr6\DoctrineProvider which does not imple  
  ment Psr\SimpleCache\CacheInterface.
```

If I load a homepage, I have this result :
```
Fatal error: Uncaught InvalidArgumentException: Cache provided for type "meta" is Doctrine\Common\Cache\Psr6\DoctrineProvider which does not implement Psr\SimpleCache\CacheInterface. in /var/www/html/vendor/jackalope/jackalope-doctrine-dbal/src/Jackalope/Transport/DoctrineDBAL/CachedClient.php:44 Stack trace: #0 [internal function]: Jackalope\Transport\DoctrineDBAL\CachedClient->__construct(Object(Jackalope\Factory), Object(Doctrine\DBAL\Connection), Array) #1 /var/www/html/vendor/jackalope/jackalope/src/Jackalope/Factory.php(51): ReflectionClass->newInstanceArgs(Array) #2 /var/www/html/vendor/jackalope/jackalope-doctrine-dbal/src/Jackalope/RepositoryFactoryDoctrineDBAL.php(116): Jackalope\Factory->get('Jackalope\\Trans...', Array) #3 /var/www/html/var/cache/website/stage/ContainerNxHRUJT/App_KernelStageContainer.php(3495): Jackalope\RepositoryFactoryDoctrineDBAL->getRepository(Array) #4 /var/www/html/var/cache/website/stage/ContainerNxHRUJT/App_KernelStageContainer.php(3492): ContainerNxHRUJT\App_KernelStageContainer::getSuluDocumentManager_DecoratedDefaultSessionService(Object(ContainerNxHRUJT\App_KernelStageContainer), Object(ContainerNxHRUJT\SessionGhost0025676)) #5 /var/www/html/vendor/symfony/var-exporter/Internal/LazyObjectState.php(59): ContainerNxHRUJT\App_KernelStageContainer::ContainerNxHRUJT\{closure}(Object(ContainerNxHRUJT\SessionGhost0025676)) #6 /var/www/html/vendor/symfony/var-exporter/LazyGhostTrait.php(129): Symfony\Component\VarExporter\Internal\LazyObjectState-
```

# Expected Behavior

```
// Clearing the cache for the stage environment with debug false                                      

                                                                                                       
 [OK] Cache for the "stage" environment (debug=false) was successfully cleared.
```

# Steps to Reproduce
I don't know, because in dev of APP_ENV, I have not problem, just in prod et stage at the time of deployment.
I haven't problem in version 2.5.x

Processus of deployment :
      - rm -rf var/cache/*
      - yarn install
      - composer install --prefer-dist --no-dev
      - yarn build
      - bin/console asset:install
      - bin/adminconsole sulu:admin:update-build
      - bin/console sulu:media:format:cache:cleanup
      - bin/console sulu:media:regenerate-formats
      - bin/console sulu:website:dump-sitemap
      - rm -rf var/cache/*
      - bin/console cache:warmup

# Possible Solutions

**Comment by alexander-schranz** [comment]
@lesmyrmidons check if you did correctly update your sulu_document_managsr config. See skeleton as reference. Jackalope 2 uses psr cache and jacklope 1 doctrime cache depending on your installed version you need correctly define the cache.

Cache is only used in prod/stage env that is why it does not error on dev.

**Comment by lesmyrmidons** [comment]
@alexander-schranz oh ! Good my problem is resolved
